# docker compose --env-file src/laravel/.env up -d
x-app: &app
  image: ghcr.io/gamerclassn7/laravel-mdm-server:latest
  build: .
  env_file: src/laravel/.env
  environment:
    DB_HOST: database
  volumes:
    - storage:/var/www/storage
  restart: unless-stopped
  depends_on:
    - database

services:
  app:
    <<: *app
    ports:
      - "8000:8000"

  reverb:
    <<: *app
    environment:
      DB_HOST: database
      CONTAINER_ROLE: reverb
    ports:
      - "8080:8080"

  scheduler:
    <<: *app
    environment:
      DB_HOST: database
      CONTAINER_ROLE: scheduler

  database:
    image: mysql:8.0
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  storage:
  db-data:
